[package]
name = "keyoxide"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.3"
base64 = "0.22.1"
bincode = "1.3.3"
dirs = "5.0.1"
serde = { version = "1.0.213", features = ["derive"] }
thiserror = "1.0.65"
